---
services:
  mariadb:
    image: mariadb:lts-noble
    container_name: mariadb-galera
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    network_mode: host
    volumes:
      - ./data:/var/lib/mysql
      - ./galera.cnf:/etc/mysql/conf.d/galera.cnf
